### ISSUE TITLE
[BUG] SystemError: Parent module 'plugins' not loaded, cannot perform relative import

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#111]
```
Traceback (most recent call last):
  File "bank2ynab.py", line 463, in <module>
    b2y = Bank2Ynab(get_configs(), __PY2)
  File "bank2ynab.py", line 436, in __init__
    bank_object = build_bank(bank_config)
  File "bank2ynab.py", line 415, in build_bank
    p_mod = importlib.import_module(".{}".format(plugin_module), "plugins")
  File "C:\Users\nocalla\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 981, in _gcd_import
  File "<frozen importlib._bootstrap>", line 931, in _sanity_check
```

Looks like it's failing when trying to import the plugin folder.

**Comment by nocalla** [comment]
@toyg - can you tell what's going on here? Looks like the plugin folder import folder can't be done by relative import - should we specify an absolute path? Module import confuses me...

**Comment by toyg** [comment]
fixed. I'm sure I had this before btw
