### ISSUE TITLE
Python 2: TypeError: "delimiter" must be string, not unicode

### ISSUE THREAD

**Issue by nocalla** [torbengb/bank2ynab#59]
Let's fix this bad boy.

**Comment by torbengb** [comment]
Wait, I've downloaded fresh, unmodified unicode files from my bank. Test results per branch:

py2 `master`:

```
Your specified download directory was not found: /home/torben/Downloadsx
Parsing file: elbi_umsaetze_20171025234336.csv
Using format: AT Raiffeisen Bank
Traceback (most recent call last):
  File "bank2ynab.py", line 179, in <module>
    main()
  File "bank2ynab.py", line 169, in main
    output = clean_data(file)
  File "bank2ynab.py", line 73, in clean_data
    transaction_reader = csv.reader(transaction_file, delimiter = delim)
TypeError: "delimiter" must be string, not unicode
```

py3 `master`:

```
Your specified download directory was not found: /home/torben/Downloadsx
Parsing file: elbi_umsaetze_20171025234336.csv
Using format: AT Raiffeisen Bank
Traceback (most recent call last):
  File "bank2ynab.py", line 179, in <module>
    main()
  File "bank2ynab.py", line 169, in main
    output = clean_data(file)
  File "bank2ynab.py", line 76, in clean_data
    for row in transaction_reader:
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 21: invalid continuation byte
```

py2 `better-output`:

```
Your specified download directory was not found: /home/torben/Downloadsx
Parsing file: elbi_umsaetze_20171025234336.csv
Using format: AT Raiffeisen Bank
Traceback (most recent call last):
  File "bank2ynab-better-output.py", line 184, in <module>
    main()
  File "bank2ynab-better-output.py", line 174, in main
    output = clean_data(file)
  File "bank2ynab-better-output.py", line 78, in clean_data
    transaction_reader = csv.reader(transaction_file, delimiter = delim)
TypeError: "delimiter" must be string, not unicode
```

py3 `better-output`:

```
Your specified download directory was not found: /home/torben/Downloadsx
Parsing file: elbi_umsaetze_20171025234336.csv
Using format: AT Raiffeisen Bank
Traceback (most recent call last):
  File "bank2ynab-better-output.py", line 184, in <module>
    main()
  File "bank2ynab-better-output.py", line 174, in main
    output = clean_data(file)
  File "bank2ynab-better-output.py", line 81, in clean_data
    for row in transaction_reader:
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 21: invalid continuation byte
```

py2 `issue-25`:

```
Your specified download directory was not found: /home/torben/Downloadsx
Parsing file: elbi_umsaetze_20171025234336.csv
Using format: AT Raiffeisen Bank
Traceback (most recent call last):
  File "bank2ynab-issue-25.py", line 221, in <module>
    main()
  File "bank2ynab-issue-25.py", line 210, in main
    output = clean_data(file)
  File "bank2ynab-issue-25.py", line 90, in clean_data
    transaction_reader = csv.reader(transaction_file, delimiter=delim)
TypeError: "delimiter" must be string, not unicode
```

py3 `issue-25`:

```
Your specified download directory was not found: /home/torben/Downloadsx
Parsing file: elbi_umsaetze_20171025234336.csv
Using format: AT Raiffeisen Bank
Traceback (most recent call last):
  File "bank2ynab-issue-25.py", line 221, in <module>
    main()
  File "bank2ynab-issue-25.py", line 210, in main
    output = clean_data(file)
  File "bank2ynab-issue-25.py", line 93, in clean_data
    for row in transaction_reader:
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 21: invalid continuation byte
```

**Comment by nocalla** [comment]
"UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position
21: invalid continuation byte" merits an issue so!

**Comment by torbengb** [comment]
I'll create issue #60 for this py3 error. Damn.

**Comment by toyg** [comment]
@torbengb pull and try again with master, on either python version. Hopefully it's all gone away.

**Comment by nocalla** [comment]
Now we play the waiting game! We need to get Travis up and running alright.

**Comment by torbengb** [comment]
Wow you both have been busy!
I did a new test with the code currently in master. Works fine in Py3. Sadly, this error in Py2:

```
Parsing file: elbi_umsaetze_20171027233706.csv
Traceback (most recent call last):
  File "bank2ynab.py", line 341, in <module>
    main(get_configs())
  File "bank2ynab.py", line 329, in main
    output = clean_data(file)
  File "bank2ynab.py", line 220, in clean_data
    with CrossversionCsvReader(file_path, __PY2, delimiter=delim) as transaction_reader:
  File "bank2ynab.py", line 68, in __enter__
    self.stream = open(self.file_path, encoding=encoding)
TypeError: 'encoding' is an invalid keyword argument for this function
```

**Comment by toyg** [comment]
git pull and try again. The error is somehow due to py2 detection not working, and the program going down the py3 path; it's weird because for me it works fine. I tried being a bit more explicit just in case.

If it still does not work, can you send me the output of `python --version` please? Am working on 2.7.10 / 3.6.1 here and I wonder if there is a difference.

**Comment by torbengb** [comment]
# SUCCESS

I've just grabbed the current master again and tested using Py2 and Py3, and both work perfectly. I honestly can't think of anything more to break now! Given this, I am going to close this ticket. 

## GOOD JOB!!!
